/* Generated by Yosys 0.27+3 (git sha1 b58664d4417, gcc 12.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* src = "Design_Sources/showstudentID.v:70.1-99.10" *)
module chose8to1(I0, I1, I2, I3, I4, I5, I6, I7, OUT, C);
  (* src = "Design_Sources/showstudentID.v:80.21-80.22" *)
  input [2:0] C;
  wire [2:0] C;
  (* src = "Design_Sources/showstudentID.v:71.21-71.23" *)
  input [3:0] I0;
  wire [3:0] I0;
  (* src = "Design_Sources/showstudentID.v:72.21-72.23" *)
  input [3:0] I1;
  wire [3:0] I1;
  (* src = "Design_Sources/showstudentID.v:73.21-73.23" *)
  input [3:0] I2;
  wire [3:0] I2;
  (* src = "Design_Sources/showstudentID.v:74.21-74.23" *)
  input [3:0] I3;
  wire [3:0] I3;
  (* src = "Design_Sources/showstudentID.v:75.21-75.23" *)
  input [3:0] I4;
  wire [3:0] I4;
  (* src = "Design_Sources/showstudentID.v:76.21-76.23" *)
  input [3:0] I5;
  wire [3:0] I5;
  (* src = "Design_Sources/showstudentID.v:77.21-77.23" *)
  input [3:0] I6;
  wire [3:0] I6;
  (* src = "Design_Sources/showstudentID.v:78.21-78.23" *)
  input [3:0] I7;
  wire [3:0] I7;
  (* src = "Design_Sources/showstudentID.v:79.22-79.25" *)
  output [3:0] OUT;
  wire [3:0] OUT;
  (* module_not_derived = 32'd1 *)
  (* src = "Design_Sources/showstudentID.v:85.25-96.14" *)
  chose8to1_1 \genblk1[0].chose_blk  (
    .I0(I0[0]),
    .I1(I1[0]),
    .I2(I2[0]),
    .I3(I3[0]),
    .I4(I4[0]),
    .I5(I5[0]),
    .I6(I6[0]),
    .I7(I7[0]),
    .OUT(OUT[3]),
    .chose_sig(C)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Design_Sources/showstudentID.v:85.25-96.14" *)
  chose8to1_1 \genblk1[1].chose_blk  (
    .I0(I0[1]),
    .I1(I1[1]),
    .I2(I2[1]),
    .I3(I3[1]),
    .I4(I4[1]),
    .I5(I5[1]),
    .I6(I6[1]),
    .I7(I7[1]),
    .OUT(OUT[2]),
    .chose_sig(C)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Design_Sources/showstudentID.v:85.25-96.14" *)
  chose8to1_1 \genblk1[2].chose_blk  (
    .I0(I0[2]),
    .I1(I1[2]),
    .I2(I2[2]),
    .I3(I3[2]),
    .I4(I4[2]),
    .I5(I5[2]),
    .I6(I6[2]),
    .I7(I7[2]),
    .OUT(OUT[1]),
    .chose_sig(C)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Design_Sources/showstudentID.v:85.25-96.14" *)
  chose8to1_1 \genblk1[3].chose_blk  (
    .I0(I0[3]),
    .I1(I1[3]),
    .I2(I2[3]),
    .I3(I3[3]),
    .I4(I4[3]),
    .I5(I5[3]),
    .I6(I6[3]),
    .I7(I7[3]),
    .OUT(OUT[0]),
    .chose_sig(C)
  );
endmodule

(* src = "Design_Sources/showstudentID.v:49.1-69.10" *)
module chose8to1_1(I0, I1, I2, I3, I4, I5, I6, I7, OUT, chose_sig);
  (* src = "Design_Sources/showstudentID.v:61.19-61.38" *)
  wire _00_;
  (* src = "Design_Sources/showstudentID.v:62.14-62.33" *)
  wire _01_;
  (* src = "Design_Sources/showstudentID.v:63.14-63.33" *)
  wire _02_;
  (* src = "Design_Sources/showstudentID.v:64.14-64.33" *)
  wire _03_;
  (* src = "Design_Sources/showstudentID.v:65.14-65.33" *)
  wire _04_;
  (* src = "Design_Sources/showstudentID.v:66.14-66.33" *)
  wire _05_;
  (* src = "Design_Sources/showstudentID.v:67.14-67.33" *)
  wire _06_;
  (* src = "Design_Sources/showstudentID.v:68.14-68.33" *)
  wire _07_;
  (* src = "Design_Sources/showstudentID.v:61.19-61.33" *)
  wire _08_;
  (* src = "Design_Sources/showstudentID.v:62.14-62.28" *)
  wire _09_;
  (* src = "Design_Sources/showstudentID.v:63.14-63.28" *)
  wire _10_;
  (* src = "Design_Sources/showstudentID.v:64.14-64.28" *)
  wire _11_;
  (* src = "Design_Sources/showstudentID.v:65.14-65.28" *)
  wire _12_;
  (* src = "Design_Sources/showstudentID.v:66.14-66.28" *)
  wire _13_;
  (* src = "Design_Sources/showstudentID.v:67.14-67.28" *)
  wire _14_;
  (* src = "Design_Sources/showstudentID.v:68.14-68.28" *)
  wire _15_;
  (* src = "Design_Sources/showstudentID.v:61.18-62.34" *)
  wire _16_;
  (* src = "Design_Sources/showstudentID.v:61.18-63.34" *)
  wire _17_;
  (* src = "Design_Sources/showstudentID.v:61.18-64.34" *)
  wire _18_;
  (* src = "Design_Sources/showstudentID.v:61.18-65.34" *)
  wire _19_;
  (* src = "Design_Sources/showstudentID.v:61.18-66.34" *)
  wire _20_;
  (* src = "Design_Sources/showstudentID.v:61.18-67.34" *)
  wire _21_;
  (* src = "Design_Sources/showstudentID.v:50.15-50.17" *)
  input I0;
  wire I0;
  (* src = "Design_Sources/showstudentID.v:51.15-51.17" *)
  input I1;
  wire I1;
  (* src = "Design_Sources/showstudentID.v:52.15-52.17" *)
  input I2;
  wire I2;
  (* src = "Design_Sources/showstudentID.v:53.15-53.17" *)
  input I3;
  wire I3;
  (* src = "Design_Sources/showstudentID.v:54.15-54.17" *)
  input I4;
  wire I4;
  (* src = "Design_Sources/showstudentID.v:55.15-55.17" *)
  input I5;
  wire I5;
  (* src = "Design_Sources/showstudentID.v:56.15-56.17" *)
  input I6;
  wire I6;
  (* src = "Design_Sources/showstudentID.v:57.15-57.17" *)
  input I7;
  wire I7;
  (* src = "Design_Sources/showstudentID.v:58.16-58.19" *)
  output OUT;
  wire OUT;
  (* src = "Design_Sources/showstudentID.v:59.21-59.30" *)
  input [2:0] chose_sig;
  wire [2:0] chose_sig;
  assign _00_ = _08_ & (* src = "Design_Sources/showstudentID.v:61.19-61.38" *) I0;
  assign _01_ = _09_ & (* src = "Design_Sources/showstudentID.v:62.14-62.33" *) I1;
  assign _02_ = _10_ & (* src = "Design_Sources/showstudentID.v:63.14-63.33" *) I2;
  assign _03_ = _11_ & (* src = "Design_Sources/showstudentID.v:64.14-64.33" *) I3;
  assign _04_ = _12_ & (* src = "Design_Sources/showstudentID.v:65.14-65.33" *) I4;
  assign _05_ = _13_ & (* src = "Design_Sources/showstudentID.v:66.14-66.33" *) I5;
  assign _06_ = _14_ & (* src = "Design_Sources/showstudentID.v:67.14-67.33" *) I6;
  assign _07_ = _15_ & (* src = "Design_Sources/showstudentID.v:68.14-68.33" *) I7;
  assign _08_ = ! (* src = "Design_Sources/showstudentID.v:61.19-61.33" *) chose_sig;
  assign _09_ = chose_sig == (* src = "Design_Sources/showstudentID.v:62.14-62.28" *) 3'h1;
  assign _10_ = chose_sig == (* src = "Design_Sources/showstudentID.v:63.14-63.28" *) 3'h2;
  assign _11_ = chose_sig == (* src = "Design_Sources/showstudentID.v:64.14-64.28" *) 3'h3;
  assign _12_ = chose_sig == (* src = "Design_Sources/showstudentID.v:65.14-65.28" *) 3'h4;
  assign _13_ = chose_sig == (* src = "Design_Sources/showstudentID.v:66.14-66.28" *) 3'h5;
  assign _14_ = chose_sig == (* src = "Design_Sources/showstudentID.v:67.14-67.28" *) 3'h6;
  assign _15_ = chose_sig == (* src = "Design_Sources/showstudentID.v:68.14-68.28" *) 3'h7;
  assign _16_ = _00_ | (* src = "Design_Sources/showstudentID.v:61.18-62.34" *) _01_;
  assign _17_ = _16_ | (* src = "Design_Sources/showstudentID.v:61.18-63.34" *) _02_;
  assign _18_ = _17_ | (* src = "Design_Sources/showstudentID.v:61.18-64.34" *) _03_;
  assign _19_ = _18_ | (* src = "Design_Sources/showstudentID.v:61.18-65.34" *) _04_;
  assign _20_ = _19_ | (* src = "Design_Sources/showstudentID.v:61.18-66.34" *) _05_;
  assign _21_ = _20_ | (* src = "Design_Sources/showstudentID.v:61.18-67.34" *) _06_;
  assign OUT = _21_ | (* src = "Design_Sources/showstudentID.v:61.18-68.34" *) _07_;
endmodule

(* src = "Design_Sources/showstudentID.v:33.1-47.10" *)
module decoder_3to8(INPUT, OUT);
  (* src = "Design_Sources/showstudentID.v:39.23-39.34" *)
  wire _00_;
  (* src = "Design_Sources/showstudentID.v:39.23-39.40" *)
  wire _01_;
  (* src = "Design_Sources/showstudentID.v:39.23-39.46" *)
  wire _02_;
  (* src = "Design_Sources/showstudentID.v:40.23-40.45" *)
  wire _03_;
  (* src = "Design_Sources/showstudentID.v:41.23-41.39" *)
  wire _04_;
  (* src = "Design_Sources/showstudentID.v:41.23-41.45" *)
  wire _05_;
  (* src = "Design_Sources/showstudentID.v:42.23-42.44" *)
  wire _06_;
  (* src = "Design_Sources/showstudentID.v:43.23-43.39" *)
  wire _07_;
  (* src = "Design_Sources/showstudentID.v:43.23-43.45" *)
  wire _08_;
  (* src = "Design_Sources/showstudentID.v:44.23-44.44" *)
  wire _09_;
  (* src = "Design_Sources/showstudentID.v:45.23-45.38" *)
  wire _10_;
  (* src = "Design_Sources/showstudentID.v:45.23-45.44" *)
  wire _11_;
  (* src = "Design_Sources/showstudentID.v:46.23-46.43" *)
  wire _12_;
  (* src = "Design_Sources/showstudentID.v:39.35-39.40" *)
  wire _13_;
  (* src = "Design_Sources/showstudentID.v:39.41-39.46" *)
  wire _14_;
  (* src = "Design_Sources/showstudentID.v:37.16-37.17" *)
  wire [3:0] I;
  (* src = "Design_Sources/showstudentID.v:34.25-34.30" *)
  input [2:0] INPUT;
  wire [2:0] INPUT;
  (* src = "Design_Sources/showstudentID.v:35.26-35.29" *)
  output [7:0] OUT;
  wire [7:0] OUT;
  assign _02_ = _01_ & (* src = "Design_Sources/showstudentID.v:39.23-39.46" *) _14_;
  assign _01_ = _00_ & (* src = "Design_Sources/showstudentID.v:40.23-40.40" *) _13_;
  assign _03_ = _01_ & (* src = "Design_Sources/showstudentID.v:40.23-40.45" *) INPUT[0];
  assign _05_ = _04_ & (* src = "Design_Sources/showstudentID.v:41.23-41.45" *) _14_;
  assign _04_ = _00_ & (* src = "Design_Sources/showstudentID.v:42.23-42.39" *) INPUT[1];
  assign _06_ = _04_ & (* src = "Design_Sources/showstudentID.v:42.23-42.44" *) INPUT[0];
  assign _07_ = INPUT[2] & (* src = "Design_Sources/showstudentID.v:43.23-43.39" *) _13_;
  assign _08_ = _07_ & (* src = "Design_Sources/showstudentID.v:43.23-43.45" *) _14_;
  assign _09_ = _07_ & (* src = "Design_Sources/showstudentID.v:44.23-44.44" *) INPUT[0];
  assign _10_ = INPUT[2] & (* src = "Design_Sources/showstudentID.v:45.23-45.38" *) INPUT[1];
  assign _11_ = _10_ & (* src = "Design_Sources/showstudentID.v:45.23-45.44" *) _14_;
  assign _12_ = _10_ & (* src = "Design_Sources/showstudentID.v:46.23-46.43" *) INPUT[0];
  assign OUT[0] = ~ (* src = "Design_Sources/showstudentID.v:39.21-39.47" *) _02_;
  assign OUT[1] = ~ (* src = "Design_Sources/showstudentID.v:40.21-40.46" *) _03_;
  assign OUT[2] = ~ (* src = "Design_Sources/showstudentID.v:41.21-41.46" *) _05_;
  assign _00_ = ~ (* src = "Design_Sources/showstudentID.v:42.29-42.34" *) INPUT[2];
  assign OUT[3] = ~ (* src = "Design_Sources/showstudentID.v:42.21-42.45" *) _06_;
  assign _13_ = ~ (* src = "Design_Sources/showstudentID.v:43.34-43.39" *) INPUT[1];
  assign _14_ = ~ (* src = "Design_Sources/showstudentID.v:43.40-43.45" *) INPUT[0];
  assign OUT[4] = ~ (* src = "Design_Sources/showstudentID.v:43.21-43.46" *) _08_;
  assign OUT[5] = ~ (* src = "Design_Sources/showstudentID.v:44.21-44.45" *) _09_;
  assign OUT[6] = ~ (* src = "Design_Sources/showstudentID.v:45.21-45.45" *) _11_;
  assign OUT[7] = ~ (* src = "Design_Sources/showstudentID.v:46.21-46.44" *) _12_;
  assign I = { INPUT[0], INPUT[1], INPUT[2], 1'h0 };
endmodule

(* src = "Design_Sources/showstudentID.v:20.1-31.10" *)
module decoder_seg(I, seg);
  (* src = "Design_Sources/showstudentID.v:24.49-24.65" *)
  wire _000_;
  (* src = "Design_Sources/showstudentID.v:24.49-24.71" *)
  wire _001_;
  (* src = "Design_Sources/showstudentID.v:24.76-24.86" *)
  wire _002_;
  (* src = "Design_Sources/showstudentID.v:24.76-24.91" *)
  wire _003_;
  (* src = "Design_Sources/showstudentID.v:24.76-24.96" *)
  wire _004_;
  (* src = "Design_Sources/showstudentID.v:24.101-24.110" *)
  wire _005_;
  (* src = "Design_Sources/showstudentID.v:24.101-24.116" *)
  wire _006_;
  (* src = "Design_Sources/showstudentID.v:24.101-24.121" *)
  wire _007_;
  (* src = "Design_Sources/showstudentID.v:24.126-24.140" *)
  wire _008_;
  (* src = "Design_Sources/showstudentID.v:24.126-24.145" *)
  wire _009_;
  (* src = "Design_Sources/showstudentID.v:24.22-24.33" *)
  wire _010_;
  (* src = "Design_Sources/showstudentID.v:24.22-24.39" *)
  wire _011_;
  (* src = "Design_Sources/showstudentID.v:24.22-24.44" *)
  wire _012_;
  (* src = "Design_Sources/showstudentID.v:24.49-24.59" *)
  wire _013_;
  (* src = "Design_Sources/showstudentID.v:25.22-25.43" *)
  wire _014_;
  (* src = "Design_Sources/showstudentID.v:25.48-25.63" *)
  wire _015_;
  (* src = "Design_Sources/showstudentID.v:25.48-25.69" *)
  wire _016_;
  (* src = "Design_Sources/showstudentID.v:25.99-25.120" *)
  wire _017_;
  (* src = "Design_Sources/showstudentID.v:25.125-25.145" *)
  wire _018_;
  (* src = "Design_Sources/showstudentID.v:26.22-26.38" *)
  wire _019_;
  (* src = "Design_Sources/showstudentID.v:26.22-26.44" *)
  wire _020_;
  (* src = "Design_Sources/showstudentID.v:27.101-27.122" *)
  wire _021_;
  (* src = "Design_Sources/showstudentID.v:27.76-27.96" *)
  wire _022_;
  (* src = "Design_Sources/showstudentID.v:28.49-28.70" *)
  wire _023_;
  (* src = "Design_Sources/showstudentID.v:28.153-28.169" *)
  wire _024_;
  (* src = "Design_Sources/showstudentID.v:28.153-28.174" *)
  wire _025_;
  (* src = "Design_Sources/showstudentID.v:30.22-30.45" *)
  wire _026_;
  (* src = "Design_Sources/showstudentID.v:24.66-24.71" *)
  wire _027_;
  (* src = "Design_Sources/showstudentID.v:24.81-24.86" *)
  wire _028_;
  (* src = "Design_Sources/showstudentID.v:24.22-24.27" *)
  wire _029_;
  (* src = "Design_Sources/showstudentID.v:24.111-24.116" *)
  wire _030_;
  (* src = "Design_Sources/showstudentID.v:24.21-24.72" *)
  wire _031_;
  (* src = "Design_Sources/showstudentID.v:24.21-24.97" *)
  wire _032_;
  (* src = "Design_Sources/showstudentID.v:24.21-24.122" *)
  wire _033_;
  (* src = "Design_Sources/showstudentID.v:25.21-25.70" *)
  wire _034_;
  (* src = "Design_Sources/showstudentID.v:25.21-25.95" *)
  wire _035_;
  (* src = "Design_Sources/showstudentID.v:25.21-25.121" *)
  wire _036_;
  (* src = "Design_Sources/showstudentID.v:25.21-25.146" *)
  wire _037_;
  (* src = "Design_Sources/showstudentID.v:26.21-26.71" *)
  wire _038_;
  (* src = "Design_Sources/showstudentID.v:26.21-26.96" *)
  wire _039_;
  (* src = "Design_Sources/showstudentID.v:27.21-27.123" *)
  wire _040_;
  (* src = "Design_Sources/showstudentID.v:27.21-27.97" *)
  wire _041_;
  (* src = "Design_Sources/showstudentID.v:28.21-28.71" *)
  wire _042_;
  (* src = "Design_Sources/showstudentID.v:28.21-28.98" *)
  wire _043_;
  (* src = "Design_Sources/showstudentID.v:28.21-28.124" *)
  wire _044_;
  (* src = "Design_Sources/showstudentID.v:28.21-28.149" *)
  wire _045_;
  (* src = "Design_Sources/showstudentID.v:28.21-28.175" *)
  wire _046_;
  (* src = "Design_Sources/showstudentID.v:29.21-29.72" *)
  wire _047_;
  (* src = "Design_Sources/showstudentID.v:29.21-29.98" *)
  wire _048_;
  (* src = "Design_Sources/showstudentID.v:29.21-29.123" *)
  wire _049_;
  (* src = "Design_Sources/showstudentID.v:29.21-29.148" *)
  wire _050_;
  (* src = "Design_Sources/showstudentID.v:30.21-30.73" *)
  wire _051_;
  (* src = "Design_Sources/showstudentID.v:30.21-30.98" *)
  wire _052_;
  (* src = "Design_Sources/showstudentID.v:21.29-21.30" *)
  input [3:0] I;
  wire [3:0] I;
  (* src = "Design_Sources/showstudentID.v:22.30-22.33" *)
  output [6:0] seg;
  wire [6:0] seg;
  assign _014_ = _000_ & (* src = "Design_Sources/showstudentID.v:25.22-25.43" *) I[3];
  assign _016_ = _015_ & (* src = "Design_Sources/showstudentID.v:25.48-25.69" *) _027_;
  assign _004_ = _003_ & (* src = "Design_Sources/showstudentID.v:25.74-25.94" *) I[3];
  assign _017_ = _006_ & (* src = "Design_Sources/showstudentID.v:26.49-26.70" *) _027_;
  assign _018_ = _008_ & (* src = "Design_Sources/showstudentID.v:26.75-26.95" *) _027_;
  assign _009_ = _008_ & (* src = "Design_Sources/showstudentID.v:26.100-26.119" *) I[3];
  assign _003_ = _002_ & (* src = "Design_Sources/showstudentID.v:27.101-27.116" *) I[2];
  assign _021_ = _003_ & (* src = "Design_Sources/showstudentID.v:27.101-27.122" *) _027_;
  assign _011_ = _010_ & (* src = "Design_Sources/showstudentID.v:27.22-27.39" *) _030_;
  assign _000_ = _013_ & (* src = "Design_Sources/showstudentID.v:27.49-27.65" *) _030_;
  assign _001_ = _000_ & (* src = "Design_Sources/showstudentID.v:27.49-27.71" *) _027_;
  assign _022_ = _015_ & (* src = "Design_Sources/showstudentID.v:27.76-27.96" *) I[3];
  assign _002_ = I[0] & (* src = "Design_Sources/showstudentID.v:27.101-27.111" *) _028_;
  assign _023_ = _019_ & (* src = "Design_Sources/showstudentID.v:28.49-28.70" *) I[3];
  assign _013_ = _029_ & (* src = "Design_Sources/showstudentID.v:28.102-28.112" *) I[1];
  assign _024_ = _002_ & (* src = "Design_Sources/showstudentID.v:28.153-28.169" *) _030_;
  assign _025_ = _024_ & (* src = "Design_Sources/showstudentID.v:28.153-28.174" *) I[3];
  assign _020_ = _019_ & (* src = "Design_Sources/showstudentID.v:29.49-29.71" *) _027_;
  assign _019_ = _010_ & (* src = "Design_Sources/showstudentID.v:29.76-29.92" *) I[2];
  assign _007_ = _006_ & (* src = "Design_Sources/showstudentID.v:29.127-29.147" *) I[3];
  assign _008_ = _005_ & (* src = "Design_Sources/showstudentID.v:29.152-29.166" *) I[2];
  assign _010_ = _029_ & (* src = "Design_Sources/showstudentID.v:30.22-30.33" *) _028_;
  assign _026_ = _011_ & (* src = "Design_Sources/showstudentID.v:30.22-30.45" *) _027_;
  assign _012_ = _011_ & (* src = "Design_Sources/showstudentID.v:30.50-30.72" *) I[3];
  assign _015_ = _013_ & (* src = "Design_Sources/showstudentID.v:30.77-30.92" *) I[2];
  assign _005_ = I[0] & (* src = "Design_Sources/showstudentID.v:30.102-30.111" *) I[1];
  assign _006_ = _005_ & (* src = "Design_Sources/showstudentID.v:30.102-30.117" *) _030_;
  assign _028_ = ~ (* src = "Design_Sources/showstudentID.v:30.56-30.61" *) I[1];
  assign _029_ = ~ (* src = "Design_Sources/showstudentID.v:30.77-30.82" *) I[0];
  assign _030_ = ~ (* src = "Design_Sources/showstudentID.v:30.112-30.117" *) I[2];
  assign _027_ = ~ (* src = "Design_Sources/showstudentID.v:30.118-30.123" *) I[3];
  assign _032_ = _031_ | (* src = "Design_Sources/showstudentID.v:24.21-24.97" *) _004_;
  assign _033_ = _032_ | (* src = "Design_Sources/showstudentID.v:24.21-24.122" *) _007_;
  assign seg[0] = _033_ | (* src = "Design_Sources/showstudentID.v:24.21-24.146" *) _009_;
  assign _034_ = _014_ | (* src = "Design_Sources/showstudentID.v:25.21-25.70" *) _016_;
  assign _035_ = _034_ | (* src = "Design_Sources/showstudentID.v:25.21-25.95" *) _004_;
  assign _036_ = _035_ | (* src = "Design_Sources/showstudentID.v:25.21-25.121" *) _017_;
  assign _037_ = _036_ | (* src = "Design_Sources/showstudentID.v:25.21-25.146" *) _018_;
  assign seg[1] = _037_ | (* src = "Design_Sources/showstudentID.v:25.21-25.170" *) _009_;
  assign _038_ = _020_ | (* src = "Design_Sources/showstudentID.v:26.21-26.71" *) _017_;
  assign _039_ = _038_ | (* src = "Design_Sources/showstudentID.v:26.21-26.96" *) _018_;
  assign seg[2] = _039_ | (* src = "Design_Sources/showstudentID.v:26.21-26.120" *) _009_;
  assign _040_ = _041_ | (* src = "Design_Sources/showstudentID.v:27.21-27.123" *) _021_;
  assign seg[3] = _040_ | (* src = "Design_Sources/showstudentID.v:27.21-27.147" *) _009_;
  assign _031_ = _012_ | (* src = "Design_Sources/showstudentID.v:27.21-27.72" *) _001_;
  assign _041_ = _031_ | (* src = "Design_Sources/showstudentID.v:27.21-27.97" *) _022_;
  assign _042_ = _012_ | (* src = "Design_Sources/showstudentID.v:28.21-28.71" *) _023_;
  assign _043_ = _042_ | (* src = "Design_Sources/showstudentID.v:28.21-28.98" *) _001_;
  assign _044_ = _043_ | (* src = "Design_Sources/showstudentID.v:28.21-28.124" *) _014_;
  assign _045_ = _044_ | (* src = "Design_Sources/showstudentID.v:28.21-28.149" *) _022_;
  assign _046_ = _045_ | (* src = "Design_Sources/showstudentID.v:28.21-28.175" *) _025_;
  assign seg[4] = _046_ | (* src = "Design_Sources/showstudentID.v:28.21-28.199" *) _009_;
  assign _047_ = _012_ | (* src = "Design_Sources/showstudentID.v:29.21-29.72" *) _020_;
  assign _048_ = _047_ | (* src = "Design_Sources/showstudentID.v:29.21-29.98" *) _023_;
  assign _049_ = _048_ | (* src = "Design_Sources/showstudentID.v:29.21-29.123" *) _022_;
  assign _050_ = _049_ | (* src = "Design_Sources/showstudentID.v:29.21-29.148" *) _007_;
  assign seg[5] = _050_ | (* src = "Design_Sources/showstudentID.v:29.21-29.172" *) _009_;
  assign _051_ = _026_ | (* src = "Design_Sources/showstudentID.v:30.21-30.73" *) _012_;
  assign _052_ = _051_ | (* src = "Design_Sources/showstudentID.v:30.21-30.98" *) _022_;
  assign seg[6] = _052_ | (* src = "Design_Sources/showstudentID.v:30.21-30.124" *) _017_;
endmodule

(* top =  1  *)
(* src = "Design_Sources/showstudentID.v:101.1-166.10" *)
module showstudentID(clock_sig, SEG, choseLED);
  (* src = "Design_Sources/showstudentID.v:150.20-150.31" *)
  wire [31:0] _00_;
  (* src = "Design_Sources/showstudentID.v:152.12-152.27" *)
  wire _01_;
  (* src = "Design_Sources/showstudentID.v:141.16-141.29" *)
  wire [2:0] _02_;
  (* src = "Design_Sources/showstudentID.v:116.96-116.99" *)
  wire [3:0] BUS;
  (* src = "Design_Sources/showstudentID.v:126.16-126.22" *)
  wire [2:0] CREG_w;
  (* src = "Design_Sources/showstudentID.v:116.16-116.24" *)
  wire [3:0] IDREG_w0;
  (* src = "Design_Sources/showstudentID.v:116.26-116.34" *)
  wire [3:0] IDREG_w1;
  (* src = "Design_Sources/showstudentID.v:116.36-116.44" *)
  wire [3:0] IDREG_w2;
  (* src = "Design_Sources/showstudentID.v:116.46-116.54" *)
  wire [3:0] IDREG_w3;
  (* src = "Design_Sources/showstudentID.v:116.56-116.64" *)
  wire [3:0] IDREG_w4;
  (* src = "Design_Sources/showstudentID.v:116.66-116.74" *)
  wire [3:0] IDREG_w5;
  (* src = "Design_Sources/showstudentID.v:116.76-116.84" *)
  wire [3:0] IDREG_w6;
  (* src = "Design_Sources/showstudentID.v:116.86-116.94" *)
  wire [3:0] IDREG_w7;
  (* src = "Design_Sources/showstudentID.v:103.18-103.21" *)
  output [6:0] SEG;
  wire [6:0] SEG;
  (* src = "Design_Sources/showstudentID.v:125.15-125.20" *)
  reg [2:0] c_REG;
  (* src = "Design_Sources/showstudentID.v:104.18-104.26" *)
  output [7:0] choseLED;
  wire [7:0] choseLED;
  (* src = "Design_Sources/showstudentID.v:102.11-102.20" *)
  input clock_sig;
  wire clock_sig;
  (* src = "Design_Sources/showstudentID.v:148.16-148.23" *)
  reg [31:0] counter = 32'd0;
  (* src = "Design_Sources/showstudentID.v:106.15-106.25" *)
  reg [3:0] studentID0 = 4'h2;
  (* src = "Design_Sources/showstudentID.v:107.15-107.25" *)
  reg [3:0] studentID1 = 4'h1;
  (* src = "Design_Sources/showstudentID.v:108.15-108.25" *)
  reg [3:0] studentID2 = 4'h1;
  (* src = "Design_Sources/showstudentID.v:109.15-109.25" *)
  reg [3:0] studentID3 = 4'h5;
  (* src = "Design_Sources/showstudentID.v:110.15-110.25" *)
  reg [3:0] studentID4 = 4'h0;
  (* src = "Design_Sources/showstudentID.v:111.15-111.25" *)
  reg [3:0] studentID5 = 4'h2;
  (* src = "Design_Sources/showstudentID.v:112.15-112.25" *)
  reg [3:0] studentID6 = 4'h0;
  (* src = "Design_Sources/showstudentID.v:113.15-113.25" *)
  reg [3:0] studentID7 = 4'h0;
  (* src = "Design_Sources/showstudentID.v:114.15-114.25" *)
  reg [3:0] studentID8 = 4'h8;
  (* src = "Design_Sources/showstudentID.v:115.15-115.25" *)
  reg [3:0] studentID9 = 4'hf;
  assign _00_ = counter + (* src = "Design_Sources/showstudentID.v:150.20-150.31" *) 32'd1;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) counter <= 32'd0;
    else counter <= _00_;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID0 <= studentID1;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID1 <= studentID2;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID2 <= studentID3;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID3 <= studentID4;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID4 <= studentID5;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID5 <= studentID6;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID6 <= studentID7;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID7 <= studentID8;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID8 <= studentID9;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    if (_01_) studentID9 <= studentID0;
  assign _01_ = counter == (* src = "Design_Sources/showstudentID.v:152.12-152.27" *) 32'd1000;
  (* src = "Design_Sources/showstudentID.v:149.5-165.8" *)
  always @(posedge clock_sig)
    c_REG <= counter[2:0];
  assign _02_ = 3'h7 - (* src = "Design_Sources/showstudentID.v:141.16-141.29" *) c_REG;
  (* module_not_derived = 32'd1 *)
  (* src = "Design_Sources/showstudentID.v:140.18-143.6" *)
  decoder_3to8 C_LED (
    .INPUT(_02_),
    .OUT(choseLED)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Design_Sources/showstudentID.v:128.15-139.6" *)
  chose8to1 OUT_SUB (
    .C(c_REG),
    .I0(studentID0),
    .I1(studentID1),
    .I2(studentID2),
    .I3(studentID3),
    .I4(studentID4),
    .I5(studentID5),
    .I6(studentID6),
    .I7(studentID7),
    .OUT(BUS)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Design_Sources/showstudentID.v:144.17-147.6" *)
  decoder_seg num2seg (
    .I(BUS),
    .seg(SEG)
  );
  assign CREG_w = c_REG;
  assign IDREG_w0 = studentID0;
  assign IDREG_w1 = studentID1;
  assign IDREG_w2 = studentID2;
  assign IDREG_w3 = studentID3;
  assign IDREG_w4 = studentID4;
  assign IDREG_w5 = studentID5;
  assign IDREG_w6 = studentID6;
  assign IDREG_w7 = studentID7;
endmodule
