/* Generated by Yosys 0.27+3 (git sha1 b58664d4417, gcc 12.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* top =  1  *)
(* src = "./Design Sources/decoder32.v:22.1-32.10" *)
module decoder32(INPUT, OUTPUT);
  (* src = "./Design Sources/decoder32.v:23.21-23.26" *)
  input [4:0] INPUT;
  wire [4:0] INPUT;
  (* src = "./Design Sources/decoder32.v:24.23-24.29" *)
  output [31:0] OUTPUT;
  wire [31:0] OUTPUT;
  assign OUTPUT[0] = ! (* src = "./Design Sources/decoder32.v:29.33-29.43" *) INPUT;
  assign OUTPUT[9] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h09;
  assign OUTPUT[10] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h0a;
  assign OUTPUT[11] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h0b;
  assign OUTPUT[12] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h0c;
  assign OUTPUT[13] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h0d;
  assign OUTPUT[14] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h0e;
  assign OUTPUT[15] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h0f;
  assign OUTPUT[16] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h10;
  assign OUTPUT[17] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h11;
  assign OUTPUT[18] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h12;
  assign OUTPUT[1] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h01;
  assign OUTPUT[19] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h13;
  assign OUTPUT[20] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h14;
  assign OUTPUT[21] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h15;
  assign OUTPUT[22] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h16;
  assign OUTPUT[23] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h17;
  assign OUTPUT[24] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h18;
  assign OUTPUT[25] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h19;
  assign OUTPUT[26] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h1a;
  assign OUTPUT[27] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h1b;
  assign OUTPUT[28] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h1c;
  assign OUTPUT[2] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h02;
  assign OUTPUT[29] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h1d;
  assign OUTPUT[30] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h1e;
  assign OUTPUT[31] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h1f;
  assign OUTPUT[3] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h03;
  assign OUTPUT[4] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h04;
  assign OUTPUT[5] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h05;
  assign OUTPUT[6] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h06;
  assign OUTPUT[7] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h07;
  assign OUTPUT[8] = INPUT == (* src = "./Design Sources/decoder32.v:29.33-29.43" *) 5'h08;
endmodule
